language: php
sudo: false

php:
  - 5.5

env:
  - DB=MYSQL CORE_RELEASE=3.5

matrix:
  include:
    - php: 5.5
      env: DB=SQLITE CORE_RELEASE=3.1
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 7.0
      env: DB=PGSQL CORE_RELEASE=3.6 COVERAGE=1
    - php: 7.0
      env: DB=PGSQL CORE_RELEASE=3.7

before_script:
  - composer self-update
  - phpenv rehash
  - tar cf ~/gitbackup.tar .git
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script: ./silvershop/tests/travis/run_build.sh

after_success: ./silvershop/tests/travis/upload_coverage.sh
